name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t docker-practical:latest .

    - name: Run Docker container
      run: docker run -d -p 8080:80 docker-practical:latest

    - name: Test the application
      run: |
        sleep 5
        curl http://localhost:8080 | grep "Welcome"